version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:9.0.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Bsb build
          command: |
            npm run clean
            npm run build
      - run:
          name: Unit tests
          command: |
            npm test
      - run: echo "hello world" # run the `echo` command
