// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ParseColor = require("../src/ParseColor.bs.js");

var c = ParseColor.parse("orange");

console.log(c);

console.log(c.rgb);

console.log(c.rgba);

console.log(c.hex);

console.log(c.keyword);

exports.c = c;
/* c Not a pure module */
