// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ParseColor = require("parse-color");

function parse(v) {
  var p = ParseColor(v);
  var match = p.hex;
  var hex = match !== undefined ? match : "";
  var match$1 = p.keyword;
  var keyword = match$1 !== undefined ? match$1 : "";
  return /* record */[
          /* keyword */keyword,
          /* hex */hex,
          /* rgb */p.rgb,
          /* hsv */p.hsv,
          /* hsl */p.hsl,
          /* cmyk */p.cmyk,
          /* rgba */p.rgba,
          /* hsla */p.hsla,
          /* hsva */p.hsva,
          /* cmyka */p.cmyka
        ];
}

function asHex(v) {
  return v[/* hex */1];
}

function asKeyword(v) {
  return v[/* keyword */0];
}

function asRgb(v) {
  return v[/* rgb */2];
}

function asRgba(v) {
  return v[/* rgba */6];
}

function asHsv(v) {
  return v[/* hsv */3];
}

function asHsva(v) {
  return v[/* hsva */8];
}

function asHsl(v) {
  return v[/* hsl */4];
}

function asHsla(v) {
  return v[/* hsla */7];
}

function asCmyk(v) {
  return v[/* cmyk */5];
}

function asCmyka(v) {
  return v[/* cmyka */9];
}

exports.parse = parse;
exports.asHex = asHex;
exports.asKeyword = asKeyword;
exports.asRgb = asRgb;
exports.asRgba = asRgba;
exports.asHsv = asHsv;
exports.asHsva = asHsva;
exports.asHsl = asHsl;
exports.asHsla = asHsla;
exports.asCmyk = asCmyk;
exports.asCmyka = asCmyka;
/* parse-color Not a pure module */
