// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("bs-jest/src/jest.js");

describe("Smoke", (function () {
        return Jest.test("toBe", (function () {
                      return Jest.Expect[/* toBe */2](3, Jest.Expect[/* expect */0](3));
                    }));
      }));

/*  Not a pure module */
