// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var ParseColor = require("../src/ParseColor.bs.js");

Jest.describe("Free smoke free smokkkkeee", (function (param) {
        return Jest.test("1 + 2 = 3", (function (param) {
                      return Jest.Expect.toBe(3, Jest.Expect.expect(3));
                    }));
      }));

Jest.describe("parse", (function (param) {
        Jest.test("Hex #ffa500", (function (param) {
                var t = ParseColor.parse("#ffa500");
                return Jest.Expect.toEqual({
                            keyword: "orange",
                            hex: "#ffa500",
                            rgb: /* tuple */[
                              255,
                              165,
                              0
                            ],
                            hsv: /* tuple */[
                              39,
                              100,
                              100
                            ],
                            hsl: /* tuple */[
                              39,
                              100,
                              50
                            ],
                            cmyk: /* tuple */[
                              0,
                              35,
                              100,
                              0
                            ],
                            rgba: /* tuple */[
                              255,
                              165,
                              0,
                              1.0
                            ],
                            hsla: /* tuple */[
                              39,
                              100,
                              50,
                              1.0
                            ],
                            hsva: /* tuple */[
                              39,
                              100,
                              100,
                              1.0
                            ],
                            cmyka: /* tuple */[
                              0,
                              35,
                              100,
                              0,
                              1.0
                            ]
                          }, Jest.Expect.expect(t));
              }));
        Jest.test("Hex #333", (function (param) {
                var t = ParseColor.parse("#333");
                return Jest.Expect.toEqual({
                            keyword: "",
                            hex: "#333333",
                            rgb: /* tuple */[
                              51,
                              51,
                              51
                            ],
                            hsv: /* tuple */[
                              0,
                              0,
                              20
                            ],
                            hsl: /* tuple */[
                              0,
                              0,
                              20
                            ],
                            cmyk: /* tuple */[
                              0,
                              0,
                              0,
                              80
                            ],
                            rgba: /* tuple */[
                              51,
                              51,
                              51,
                              1.0
                            ],
                            hsla: /* tuple */[
                              0,
                              0,
                              20,
                              1.0
                            ],
                            hsva: /* tuple */[
                              0,
                              0,
                              20,
                              1.0
                            ],
                            cmyka: /* tuple */[
                              0,
                              0,
                              0,
                              80,
                              1.0
                            ]
                          }, Jest.Expect.expect(t));
              }));
        Jest.test("Hex #f98", (function (param) {
                var t = ParseColor.parse("#f98");
                return Jest.Expect.toEqual({
                            keyword: "",
                            hex: "#ff9988",
                            rgb: /* tuple */[
                              255,
                              153,
                              136
                            ],
                            hsv: /* tuple */[
                              9,
                              47,
                              100
                            ],
                            hsl: /* tuple */[
                              9,
                              100,
                              77
                            ],
                            cmyk: /* tuple */[
                              0,
                              40,
                              47,
                              0
                            ],
                            rgba: /* tuple */[
                              255,
                              153,
                              136,
                              1.0
                            ],
                            hsla: /* tuple */[
                              9,
                              100,
                              77,
                              1.0
                            ],
                            hsva: /* tuple */[
                              9,
                              47,
                              100,
                              1.0
                            ],
                            cmyka: /* tuple */[
                              0,
                              40,
                              47,
                              0,
                              1.0
                            ]
                          }, Jest.Expect.expect(t));
              }));
        Jest.test("String 'lime'", (function (param) {
                var t = ParseColor.parse("lime");
                return Jest.Expect.toEqual({
                            keyword: "lime",
                            hex: "#00ff00",
                            rgb: /* tuple */[
                              0,
                              255,
                              0
                            ],
                            hsv: /* tuple */[
                              120,
                              100,
                              100
                            ],
                            hsl: /* tuple */[
                              120,
                              100,
                              50
                            ],
                            cmyk: /* tuple */[
                              100,
                              0,
                              100,
                              0
                            ],
                            rgba: /* tuple */[
                              0,
                              255,
                              0,
                              1
                            ],
                            hsla: /* tuple */[
                              120,
                              100,
                              50,
                              1
                            ],
                            hsva: /* tuple */[
                              120,
                              100,
                              100,
                              1
                            ],
                            cmyka: /* tuple */[
                              100,
                              0,
                              100,
                              0,
                              1
                            ]
                          }, Jest.Expect.expect(t));
              }));
        Jest.test("String hsl(210,50,50)", (function (param) {
                var t = ParseColor.parse("hsl(210,50,50)");
                return Jest.Expect.toEqual({
                            keyword: "",
                            hex: "#407fbf",
                            rgb: /* tuple */[
                              64,
                              127,
                              191
                            ],
                            hsv: /* tuple */[
                              210,
                              67,
                              75
                            ],
                            hsl: /* tuple */[
                              210,
                              50,
                              50
                            ],
                            cmyk: /* tuple */[
                              67,
                              33,
                              0,
                              25
                            ],
                            rgba: /* tuple */[
                              64,
                              127,
                              191,
                              1
                            ],
                            hsla: /* tuple */[
                              210,
                              50,
                              50,
                              1
                            ],
                            hsva: /* tuple */[
                              210,
                              67,
                              75,
                              1
                            ],
                            cmyka: /* tuple */[
                              67,
                              33,
                              0,
                              25,
                              1
                            ]
                          }, Jest.Expect.expect(t));
              }));
        return Jest.test("String rgba(153,50,204,60%)", (function (param) {
                      var t = ParseColor.parse("rgba(153,50,204,60%)");
                      return Jest.Expect.toEqual({
                                  keyword: "darkorchid",
                                  hex: "#9932cc",
                                  rgb: /* tuple */[
                                    153,
                                    50,
                                    204
                                  ],
                                  hsv: /* tuple */[
                                    280,
                                    75,
                                    80
                                  ],
                                  hsl: /* tuple */[
                                    280,
                                    61,
                                    50
                                  ],
                                  cmyk: /* tuple */[
                                    25,
                                    75,
                                    0,
                                    20
                                  ],
                                  rgba: /* tuple */[
                                    153,
                                    50,
                                    204,
                                    0.6
                                  ],
                                  hsla: /* tuple */[
                                    280,
                                    61,
                                    50,
                                    0.6
                                  ],
                                  hsva: /* tuple */[
                                    280,
                                    75,
                                    80,
                                    0.6
                                  ],
                                  cmyka: /* tuple */[
                                    25,
                                    75,
                                    0,
                                    20,
                                    0.6
                                  ]
                                }, Jest.Expect.expect(t));
                    }));
      }));

Jest.describe("extract", (function (param) {
        Jest.test("Hex #ffa500", (function (param) {
                var t = ParseColor.asHex(ParseColor.parse("#ffa500"));
                return Jest.Expect.toEqual("#ffa500", Jest.Expect.expect(t));
              }));
        Jest.test("Name #9932cc", (function (param) {
                var t = ParseColor.asKeyword(ParseColor.parse("#9932cc"));
                return Jest.Expect.toEqual("darkorchid", Jest.Expect.expect(t));
              }));
        Jest.test("Name #407fbf", (function (param) {
                var t = ParseColor.asKeyword(ParseColor.parse("#407fbf"));
                return Jest.Expect.toEqual("", Jest.Expect.expect(t));
              }));
        Jest.test("Rgb #f98", (function (param) {
                var t = ParseColor.asRgb(ParseColor.parse("#f98"));
                return Jest.Expect.toEqual(/* tuple */[
                            255,
                            153,
                            136
                          ], Jest.Expect.expect(t));
              }));
        Jest.test("Rgba #f98", (function (param) {
                var t = ParseColor.asRgba(ParseColor.parse("#f98"));
                return Jest.Expect.toEqual(/* tuple */[
                            255,
                            153,
                            136,
                            1
                          ], Jest.Expect.expect(t));
              }));
        Jest.test("Hsv #f98", (function (param) {
                var t = ParseColor.asHsv(ParseColor.parse("#f98"));
                return Jest.Expect.toEqual(/* tuple */[
                            9,
                            47,
                            100
                          ], Jest.Expect.expect(t));
              }));
        Jest.test("Hsva #f98", (function (param) {
                var t = ParseColor.asHsva(ParseColor.parse("#f98"));
                return Jest.Expect.toEqual(/* tuple */[
                            9,
                            47,
                            100,
                            1
                          ], Jest.Expect.expect(t));
              }));
        Jest.test("Hsl #f98", (function (param) {
                var t = ParseColor.asHsl(ParseColor.parse("#f98"));
                return Jest.Expect.toEqual(/* tuple */[
                            9,
                            100,
                            77
                          ], Jest.Expect.expect(t));
              }));
        Jest.test("Hsla #f98", (function (param) {
                var t = ParseColor.asHsla(ParseColor.parse("#f98"));
                return Jest.Expect.toEqual(/* tuple */[
                            9,
                            100,
                            77,
                            1
                          ], Jest.Expect.expect(t));
              }));
        Jest.test("Cmyk #f98", (function (param) {
                var t = ParseColor.asCmyk(ParseColor.parse("#f98"));
                return Jest.Expect.toEqual(/* tuple */[
                            0,
                            40,
                            47,
                            0
                          ], Jest.Expect.expect(t));
              }));
        return Jest.test("Cmyka #f98", (function (param) {
                      var t = ParseColor.asCmyka(ParseColor.parse("#f98"));
                      return Jest.Expect.toEqual(/* tuple */[
                                  0,
                                  40,
                                  47,
                                  0,
                                  1
                                ], Jest.Expect.expect(t));
                    }));
      }));

/*  Not a pure module */
